# Generic Errors
no_user_error: âŒ You have not been added to the database- please contact a member of the <@&880214274327318588>
no_user_error_third_person: âŒ They have not been added to the database.
no_user_error_third_person_several: âŒ Someone has not been added to the database.
no_user_url_error: âŒ Their Twitch username has not been added to the database.
no_user_url_error_1st_person: âŒ Your Twitch username has not been added to the database. Please use the $link command to add it.

# Generic Warnings
no_permission: âš ï¸ You are not permitted to use this command.
invalid_content_length: âš ï¸ Your command does not have enough arguments.
invalid_url: âš ï¸ That is not a url!
no_user: âš ï¸ The specified member does not exist!
cant_send_dm: âš ï¸ The bot was unable to send you a DM, do you have DMs from this server disabled?

# Specific Warnings
not_a_number: âš ï¸ The points awarded is not a number!
not_a_number_tags: âš ï¸ The tags stated is not a number!
not_a_number_weeks: âš ï¸ The weeks given is not a number!
not_a_stage: âš ï¸ Stages range between 0 and 3.
no_raid_history: âš ï¸ The specified user has never participated in a raid!
should_not_be_a_url: âš ï¸ Please do not enter your Twitch URL but instead your Twitch username
raid_history_invalid_type: âš ï¸ The second argument should either be "attendance" or "raided"
not_eligible_for_on_leave: âš ï¸ You are not eligible to go on leave
not_a_number_slot: âš ï¸ The slot provided is not a number!
not_a_slot: âš ï¸ The slot provided does not exist!
not_express_eligible: âš ï¸ The member is not Express eligible. Add "force" as a third argument to the command to override this warning.
bad_username_to_url: âš ï¸ Please change your Discord username so it contains your Twitch username.
express_slot_taken: âš ï¸ The slot specified is already taken. Add "force" as a third argument to the command to override this warning.
not_a_raid_train: âš ï¸ The raid train specified isn't a real name.
not_a_table: âš ï¸ No table in the database goes under that name.
no_onleave_record: âš ï¸ The specified member has never been On Leave!

# Success Messages
manual_user_addition: âœ… The specified user and their Twitch url are now inside of the database.
manual_url_addition: âœ… The specified user now has their twitch url attached to the database.
added_raid: âœ… The raid has now been added for the specified user(s).
point_change: âœ… The member(s) points were changed
raid_participation_removal: âœ… The specified user has no longer participated in the raid.
purge: âœ… All raid and support tags from 4 weeks ago have been purged.
person_raided: âœ… The specified streamer has been logged as raided.
on_leave_roles_purged: âœ… All members who have been On Leave for over a month have had the role revoked. Please remember to remove their role reactions.
lock_express: ğŸ”’ The Express channel is now locked, and therefore messages can now be deleted safely.
unlock_express: ğŸ”“ The Express channel is now unlocked, meaning that deleting Express tags will now affect the database.
lock_request_a_slot: ğŸ”’ The bot will now ignore Request A Slot
unlock_request_a_slot: ğŸ”“ The bot will now read Request A Slot
new_express: âœ… A new Express has been started!
added_to_express: âœ… The specified member has been added to the Express.
deleted_slot: âœ… The slot has now been cleared.
added_comment: âœ… The comment has been added.
added_tags: âœ… The tags were added.
changed_stage: âœ… The member's stage was changed.
raid_goto_confirmation: âœ… A message has been posted in
onleave_forgiven: âœ… The member's On Leave record has been forgiven.

# Specific Messages
never_been_raided: â— The specified user has never been raided in or out of community!
slot_not_taken: â— The slot is already free!
shutdown: â— The bot has been shut down.
restart: â— The bot has restarted.
no_attendance: â— No raid attendance was taken.
raid_message: |
  <@&880214274297974868> DING! DING! it's Nearly RAID TIME! The **%** Raid Train is taking off in 20 minutes!
  Come to Raid Voice Chat, 10 mins before the Raid starts and let's make this Raid Train EPIC!

  Raid Rules:
  â€¢  NO Cursing or self-promo in the Raid Voice Channel
  â€¢  NO Negativity or personal remarks towards community members
  â€¢  NO Streaming while you're raiding
  â€¢  NO talking in other discord channels
  â€¢  Raids last 30 mins, up to an hour
  â€¢  We will be dropping links in the raid-links channel every 5 mins
  â€¢  Raid attendance is taken at the end of each 30-minute raid
  â€¢  Push to talk is on but you are not required to talk or have a mic
  â€¢  You do not have to follow, sub or donate bits to any streamers 

# Activity Check Messages
stage_1: â— You failed last week's activity requirements. If you fail again next week, your level will be reset.
stage_2: â— You failed last week's activity requirements. If you fail again next week, your membership will be terminated.
stage_3: â— You failed last week's activity requirements. Because of this, you may be kicked from the server.